// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retrosharp.Data.Context;

#nullable disable

namespace Retrosharp.Data.Migrator.Migrations
{
    [DbContext(typeof(RetrosharpContext))]
    [Migration("20260718160600_GameNaturalKey")]
    partial class GameNaturalKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retrosharp.Data.Model.BallparkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("FirstGame")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastGame")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParkName")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("StateProvinceCountry")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode")
                        .IsUnique();

                    b.ToTable("Ballpark");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.BattingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("AtBats")
                        .HasColumnType("smallint");

                    b.Property<short>("BaseOnBalls")
                        .HasColumnType("smallint");

                    b.Property<short>("Doubles")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<short>("GroundedIntoDoublePlay")
                        .HasColumnType("smallint");

                    b.Property<short>("Hit")
                        .HasColumnType("smallint");

                    b.Property<short>("HitByPitches")
                        .HasColumnType("smallint");

                    b.Property<short>("Homeruns")
                        .HasColumnType("smallint");

                    b.Property<short>("IntentionalBb")
                        .HasColumnType("smallint");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<short>("PlateAppearances")
                        .HasColumnType("smallint");

                    b.Property<short>("Positions")
                        .HasColumnType("smallint");

                    b.Property<short>("Runs")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeBunts")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeFlies")
                        .HasColumnType("smallint");

                    b.Property<short?>("SeasonYear")
                        .HasColumnType("smallint");

                    b.Property<short>("StolenBases")
                        .HasColumnType("smallint");

                    b.Property<short>("Strikeouts")
                        .HasColumnType("smallint");

                    b.Property<short>("TimesCaughtStealing")
                        .HasColumnType("smallint");

                    b.Property<short>("Triples")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PersonId", "FranchiseId", "SeasonYear");

                    b.ToTable("Batting");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FieldingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("DoublePlays")
                        .HasColumnType("int");

                    b.Property<int?>("Errors")
                        .HasColumnType("int");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int?>("PassedBalls")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<int?>("Putouts")
                        .HasColumnType("int");

                    b.Property<short?>("SeasonYear")
                        .HasColumnType("smallint");

                    b.Property<int?>("TriplePlays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PersonId", "FranchiseId", "SeasonYear", "Position");

                    b.ToTable("Fielding");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FranchiseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateNickname")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DivisionCode")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FranchiseCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("FranchiseEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("FranchiseIdentifier")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FranchiseLocation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("FranchiseStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlayingCity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlayingState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseCode");

                    b.HasIndex("FranchiseIdentifier");

                    b.HasIndex("LeagueId");

                    b.HasIndex("FranchiseIdentifier", "FranchiseStart")
                        .IsUnique();

                    b.ToTable("Franchise");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameAdjustmentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AdjustmentType")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("GameId", "Sequence");

                    b.ToTable("GameAdjustment");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameBattingStatisticsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("AtBats")
                        .HasColumnType("smallint");

                    b.Property<short>("BaseOnBalls")
                        .HasColumnType("smallint");

                    b.Property<short>("Doubles")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<short>("GroundedIntoDoublePlay")
                        .HasColumnType("smallint");

                    b.Property<short>("Hit")
                        .HasColumnType("smallint");

                    b.Property<short>("HitByPitches")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeVisitor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("Homeruns")
                        .HasColumnType("smallint");

                    b.Property<short>("IntentionalBb")
                        .HasColumnType("smallint");

                    b.Property<short>("PlateAppearances")
                        .HasColumnType("smallint");

                    b.Property<short>("Runs")
                        .HasColumnType("smallint");

                    b.Property<short>("RunsBattedIn")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeBunts")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeFlies")
                        .HasColumnType("smallint");

                    b.Property<short>("StolenBases")
                        .HasColumnType("smallint");

                    b.Property<short>("Strikeouts")
                        .HasColumnType("smallint");

                    b.Property<short>("TimesCaughtStealing")
                        .HasColumnType("smallint");

                    b.Property<short>("Triples")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("GameId", "FranchiseId", "HomeVisitor");

                    b.ToTable("GameBattingStatistics");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameCommentModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "Sequence");

                    b.ToTable("GameComment");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventFieldingCreditModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreditType")
                        .HasColumnType("int");

                    b.Property<int>("GameEventId")
                        .HasColumnType("int");

                    b.Property<int>("GameEventRunnerId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<byte>("Position")
                        .HasColumnType("tinyint");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameEventId");

                    b.HasIndex("GameEventRunnerId");

                    b.HasIndex("PersonId");

                    b.ToTable("GameEventFieldingCredit");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventGameStatusModel", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ProcessedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("GameId");

                    b.ToTable("GameEventGameStatus");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Balls")
                        .HasColumnType("tinyint");

                    b.Property<int?>("BattedBallType")
                        .HasColumnType("int");

                    b.Property<int>("BatterId")
                        .HasColumnType("int");

                    b.Property<int>("EventType")
                        .HasColumnType("int");

                    b.Property<byte>("FoulBallsWithTwoStrikes")
                        .HasColumnType("tinyint");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<byte>("Inning")
                        .HasColumnType("tinyint");

                    b.Property<bool>("IsSacFly")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSacHit")
                        .HasColumnType("bit");

                    b.Property<string>("PitchSequence")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<int>("PitcherId")
                        .HasColumnType("int");

                    b.Property<string>("RawEventText")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<byte>("Strikes")
                        .HasColumnType("tinyint");

                    b.Property<string>("TeamAtBat")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("BatterId");

                    b.HasIndex("PitcherId");

                    b.HasIndex("GameId", "Sequence");

                    b.ToTable("GameEvent");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventRunnerModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("EndBase")
                        .HasColumnType("int");

                    b.Property<int>("GameEventId")
                        .HasColumnType("int");

                    b.Property<bool>("IsEarnedRun")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOut")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRBI")
                        .HasColumnType("bit");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("ResponsiblePitcherId")
                        .HasColumnType("int");

                    b.Property<int>("StartBase")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GameEventId");

                    b.HasIndex("PersonId");

                    b.HasIndex("ResponsiblePitcherId");

                    b.ToTable("GameEventRunner");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameFieldingStatisticsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Assists")
                        .HasColumnType("smallint");

                    b.Property<byte>("DoublePlays")
                        .HasColumnType("tinyint");

                    b.Property<short>("Errors")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("HomeVisitor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte>("PassedBalls")
                        .HasColumnType("tinyint");

                    b.Property<short>("Putouts")
                        .HasColumnType("smallint");

                    b.Property<byte>("TriplePlays")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("GameId", "FranchiseId", "HomeVisitor");

                    b.ToTable("GameFieldingStatistics");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameLineupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatterId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("HomeVisitor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte>("LineupOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("BatterId");

                    b.HasIndex("GameId", "BatterId");

                    b.ToTable("GameLineup");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallparkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameDayNight")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<short?>("GameLengthMinutes")
                        .HasColumnType("smallint");

                    b.Property<string>("GameNotes")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte>("GameNumber")
                        .HasColumnType("tinyint");

                    b.Property<string>("GameWeekDay")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("GameWinningBatterId")
                        .HasColumnType("int");

                    b.Property<byte?>("HomeErrors")
                        .HasColumnType("tinyint");

                    b.Property<int>("HomeFranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("HomeGameNumber")
                        .HasColumnType("int");

                    b.Property<byte?>("HomeHits")
                        .HasColumnType("tinyint");

                    b.Property<string>("HomeLineScore")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("HomeManagerId")
                        .HasColumnType("int");

                    b.Property<byte>("HomeTeamRuns")
                        .HasColumnType("tinyint");

                    b.Property<int?>("LosingPitcherId")
                        .HasColumnType("int");

                    b.Property<int?>("ParkAttendance")
                        .HasColumnType("int");

                    b.Property<int?>("SavingPitcherId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireFirstId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireLeftId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireRightId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireSecondId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireThirdId")
                        .HasColumnType("int");

                    b.Property<byte?>("VisitorErrors")
                        .HasColumnType("tinyint");

                    b.Property<int>("VisitorFranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorGameNumber")
                        .HasColumnType("int");

                    b.Property<byte?>("VisitorHits")
                        .HasColumnType("tinyint");

                    b.Property<string>("VisitorLineScore")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("VisitorManagerId")
                        .HasColumnType("int");

                    b.Property<byte>("VisitorRuns")
                        .HasColumnType("tinyint");

                    b.Property<int?>("WinningPitcherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BallparkId");

                    b.HasIndex("GameDate");

                    b.HasIndex("GameWinningBatterId");

                    b.HasIndex("HomeFranchiseId");

                    b.HasIndex("HomeManagerId");

                    b.HasIndex("LosingPitcherId");

                    b.HasIndex("SavingPitcherId");

                    b.HasIndex("UmpireFirstId");

                    b.HasIndex("UmpireHomeId");

                    b.HasIndex("UmpireLeftId");

                    b.HasIndex("UmpireRightId");

                    b.HasIndex("UmpireSecondId");

                    b.HasIndex("UmpireThirdId");

                    b.HasIndex("VisitorFranchiseId");

                    b.HasIndex("VisitorManagerId");

                    b.HasIndex("WinningPitcherId");

                    b.HasIndex("GameDate", "GameNumber", "HomeFranchiseId", "VisitorFranchiseId")
                        .IsUnique();

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GamePitchingStatisticsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("Balks")
                        .HasColumnType("tinyint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("HomeVisitor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("IndividualEarnedRuns")
                        .HasColumnType("smallint");

                    b.Property<byte>("PitchersUsed")
                        .HasColumnType("tinyint");

                    b.Property<short>("TeamEarnedRuns")
                        .HasColumnType("smallint");

                    b.Property<byte>("WildPitches")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("GameId", "FranchiseId", "HomeVisitor");

                    b.ToTable("GamePitchingStatistics");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameSubstitutionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte>("BattingOrderPosition")
                        .HasColumnType("tinyint");

                    b.Property<byte>("FieldingPosition")
                        .HasColumnType("tinyint");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("TeamAtBat")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.HasIndex("GameId", "Sequence");

                    b.ToTable("GameSubstitution");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.LeagueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LeagueCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueCode")
                        .IsUnique();

                    b.ToTable("League");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LeagueCode = "AA",
                            LeagueName = "American Association"
                        },
                        new
                        {
                            Id = 2,
                            LeagueCode = "AL",
                            LeagueName = "American League"
                        },
                        new
                        {
                            Id = 3,
                            LeagueCode = "FL",
                            LeagueName = "Federal League"
                        },
                        new
                        {
                            Id = 4,
                            LeagueCode = "NA",
                            LeagueName = "National Association"
                        },
                        new
                        {
                            Id = 5,
                            LeagueCode = "NL",
                            LeagueName = "National League"
                        },
                        new
                        {
                            Id = 6,
                            LeagueCode = "PL",
                            LeagueName = "Players League"
                        },
                        new
                        {
                            Id = 7,
                            LeagueCode = "UA",
                            LeagueName = "Union Association"
                        });
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Bats")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BirthCity")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BirthCountry")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BirthStateProvince")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Cemetery")
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("CemeteryCity")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CemeteryCountry")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CemeteryNote")
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CemeteryStateProv")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("CoachDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoachLastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeathCity")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DeathCountry")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeathStateProvince")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FullName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsHof")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ManagerDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManagerLastDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlayerDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlayerLastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RetroSheetId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Surname")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Throws")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("UmpireDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UmpireLastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UseName")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RetroSheetId")
                        .IsUnique();

                    b.HasIndex("Surname");

                    b.HasIndex("UseName");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PitchingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Balks")
                        .HasColumnType("smallint");

                    b.Property<short>("BaseOnBalls")
                        .HasColumnType("smallint");

                    b.Property<short>("CompleteGames")
                        .HasColumnType("smallint");

                    b.Property<short>("EarnedRuns")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<short>("GamesFinished")
                        .HasColumnType("smallint");

                    b.Property<short>("GamesPitched")
                        .HasColumnType("smallint");

                    b.Property<short>("GamesStarted")
                        .HasColumnType("smallint");

                    b.Property<short>("HitBatsmen")
                        .HasColumnType("smallint");

                    b.Property<short>("Hits")
                        .HasColumnType("smallint");

                    b.Property<short>("InningsPitched")
                        .HasColumnType("smallint");

                    b.Property<short>("IntentionalBb")
                        .HasColumnType("smallint");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<short>("Runs")
                        .HasColumnType("smallint");

                    b.Property<short>("Saves")
                        .HasColumnType("smallint");

                    b.Property<short>("SeasonYear")
                        .HasColumnType("smallint");

                    b.Property<short>("Shutouts")
                        .HasColumnType("smallint");

                    b.Property<short>("Strikeouts")
                        .HasColumnType("smallint");

                    b.Property<short>("WildPitches")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PersonId", "FranchiseId", "SeasonYear");

                    b.ToTable("Pitching");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.BattingModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("BattingRecords")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany("BattingRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FieldingModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FranchiseModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.LeagueModel", "League")
                        .WithMany("Franchises")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("League");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameAdjustmentModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameAdjustments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameBattingStatisticsModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("GameBattingStatistics")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameBattingStatistics")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameCommentModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameComments")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventFieldingCreditModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.GameEventModel", "GameEvent")
                        .WithMany()
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameEventRunnerModel", "GameEventRunner")
                        .WithMany()
                        .HasForeignKey("GameEventRunnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GameEvent");

                    b.Navigation("GameEventRunner");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventGameStatusModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithOne("GameEventGameStatus")
                        .HasForeignKey("Retrosharp.Data.Model.GameEventGameStatusModel", "GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Batter")
                        .WithMany()
                        .HasForeignKey("BatterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameEvents")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Pitcher")
                        .WithMany()
                        .HasForeignKey("PitcherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Batter");

                    b.Navigation("Game");

                    b.Navigation("Pitcher");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameEventRunnerModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.GameEventModel", "GameEvent")
                        .WithMany()
                        .HasForeignKey("GameEventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "ResponsiblePitcher")
                        .WithMany()
                        .HasForeignKey("ResponsiblePitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("GameEvent");

                    b.Navigation("Person");

                    b.Navigation("ResponsiblePitcher");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameFieldingStatisticsModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("GameFieldingStatistics")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameFieldingStatistics")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameLineupModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Batter")
                        .WithMany("GameLineups")
                        .HasForeignKey("BatterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameLineups")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batter");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.BallparkModel", "Ballpark")
                        .WithMany("Games")
                        .HasForeignKey("BallparkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "GameWinningBatter")
                        .WithMany("GameWinningBatterGames")
                        .HasForeignKey("GameWinningBatterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "HomeFranchise")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeFranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "HomeManager")
                        .WithMany("HomeManagerGames")
                        .HasForeignKey("HomeManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "LosingPitcher")
                        .WithMany("LosingPitcherGames")
                        .HasForeignKey("LosingPitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "SavingPitcher")
                        .WithMany("SavingPitcherGames")
                        .HasForeignKey("SavingPitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireFirst")
                        .WithMany("UmpireFirstGames")
                        .HasForeignKey("UmpireFirstId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireHome")
                        .WithMany("UmpireHomeGames")
                        .HasForeignKey("UmpireHomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireLeft")
                        .WithMany("UmpireLeftGames")
                        .HasForeignKey("UmpireLeftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireRight")
                        .WithMany("UmpireRightGames")
                        .HasForeignKey("UmpireRightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireSecond")
                        .WithMany("UmpireSecondGames")
                        .HasForeignKey("UmpireSecondId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireThird")
                        .WithMany("UmpireThirdGames")
                        .HasForeignKey("UmpireThirdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "VisitorFranchise")
                        .WithMany("VisitorGames")
                        .HasForeignKey("VisitorFranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "VisitorManager")
                        .WithMany("VisitorManagerGames")
                        .HasForeignKey("VisitorManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "WinningPitcher")
                        .WithMany("WinningPitcherGames")
                        .HasForeignKey("WinningPitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ballpark");

                    b.Navigation("GameWinningBatter");

                    b.Navigation("HomeFranchise");

                    b.Navigation("HomeManager");

                    b.Navigation("LosingPitcher");

                    b.Navigation("SavingPitcher");

                    b.Navigation("UmpireFirst");

                    b.Navigation("UmpireHome");

                    b.Navigation("UmpireLeft");

                    b.Navigation("UmpireRight");

                    b.Navigation("UmpireSecond");

                    b.Navigation("UmpireThird");

                    b.Navigation("VisitorFranchise");

                    b.Navigation("VisitorManager");

                    b.Navigation("WinningPitcher");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GamePitchingStatisticsModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("GamePitchingStatistics")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GamePitchingStatistics")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameSubstitutionModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameSubstitutions")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PitchingModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("PitchingRecords")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany("PitchingRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.BallparkModel", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FranchiseModel", b =>
                {
                    b.Navigation("BattingRecords");

                    b.Navigation("GameBattingStatistics");

                    b.Navigation("GameFieldingStatistics");

                    b.Navigation("GamePitchingStatistics");

                    b.Navigation("HomeGames");

                    b.Navigation("PitchingRecords");

                    b.Navigation("VisitorGames");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameModel", b =>
                {
                    b.Navigation("GameAdjustments");

                    b.Navigation("GameBattingStatistics");

                    b.Navigation("GameComments");

                    b.Navigation("GameEventGameStatus")
                        .IsRequired();

                    b.Navigation("GameEvents");

                    b.Navigation("GameFieldingStatistics");

                    b.Navigation("GameLineups");

                    b.Navigation("GamePitchingStatistics");

                    b.Navigation("GameSubstitutions");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.LeagueModel", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PersonModel", b =>
                {
                    b.Navigation("BattingRecords");

                    b.Navigation("GameLineups");

                    b.Navigation("GameWinningBatterGames");

                    b.Navigation("HomeManagerGames");

                    b.Navigation("LosingPitcherGames");

                    b.Navigation("PitchingRecords");

                    b.Navigation("SavingPitcherGames");

                    b.Navigation("UmpireFirstGames");

                    b.Navigation("UmpireHomeGames");

                    b.Navigation("UmpireLeftGames");

                    b.Navigation("UmpireRightGames");

                    b.Navigation("UmpireSecondGames");

                    b.Navigation("UmpireThirdGames");

                    b.Navigation("VisitorManagerGames");

                    b.Navigation("WinningPitcherGames");
                });
#pragma warning restore 612, 618
        }
    }
}
