// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Retrosharp.Data.Context;

#nullable disable

namespace Retrosharp.Data.Migrator.Migrations
{
    [DbContext(typeof(RetrosharpContext))]
    partial class RetrosharpContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Retrosharp.Data.Model.BallparkModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("FirstGame")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastGame")
                        .HasColumnType("datetime2");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SiteCode")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("StateProvinceCountry")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("SiteCode")
                        .IsUnique();

                    b.ToTable("Ballpark");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.BattingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("AtBats")
                        .HasColumnType("smallint");

                    b.Property<short>("BaseOnBalls")
                        .HasColumnType("smallint");

                    b.Property<short>("Doubles")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<short>("GroundedIntoDoublePlay")
                        .HasColumnType("smallint");

                    b.Property<short>("Hit")
                        .HasColumnType("smallint");

                    b.Property<short>("HitByPitches")
                        .HasColumnType("smallint");

                    b.Property<short>("Homeruns")
                        .HasColumnType("smallint");

                    b.Property<short>("IntentionalBb")
                        .HasColumnType("smallint");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<short>("PlateAppearances")
                        .HasColumnType("smallint");

                    b.Property<short>("Positions")
                        .HasColumnType("smallint");

                    b.Property<short>("Runs")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeBunts")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeFlies")
                        .HasColumnType("smallint");

                    b.Property<short?>("SeasonYear")
                        .HasColumnType("smallint");

                    b.Property<short>("StolenBases")
                        .HasColumnType("smallint");

                    b.Property<short>("Strikeouts")
                        .HasColumnType("smallint");

                    b.Property<short>("TimesCaughtStealing")
                        .HasColumnType("smallint");

                    b.Property<short>("Triples")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PersonId", "FranchiseId", "SeasonYear");

                    b.ToTable("Batting");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FieldingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Assists")
                        .HasColumnType("int");

                    b.Property<int?>("DoublePlays")
                        .HasColumnType("int");

                    b.Property<int?>("Errors")
                        .HasColumnType("int");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int?>("PassedBalls")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<int?>("Putouts")
                        .HasColumnType("int");

                    b.Property<short?>("SeasonYear")
                        .HasColumnType("smallint");

                    b.Property<int?>("TriplePlays")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PersonId", "FranchiseId", "SeasonYear");

                    b.ToTable("Fielding");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FranchiseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateNickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("DivisionCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("FranchiseCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<DateTime?>("FranchiseEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("FranchiseIdentifier")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("FranchiseLocation")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime>("FranchiseStart")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int?>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("PlayingCity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("PlayingState")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseCode")
                        .IsUnique();

                    b.HasIndex("FranchiseIdentifier");

                    b.HasIndex("LeagueId");

                    b.ToTable("Franchise");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameLineupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BatterId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<string>("HomeVisitor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<byte>("LineupOrder")
                        .HasColumnType("tinyint");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("BatterId");

                    b.HasIndex("GameId", "BatterId");

                    b.ToTable("GameLineup");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BallparkId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GameDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GameDayNight")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<short?>("GameLengthMinutes")
                        .HasColumnType("smallint");

                    b.Property<string>("GameNotes")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<byte>("GameNumber")
                        .HasColumnType("tinyint");

                    b.Property<string>("GameWeekDay")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int?>("GameWinningBatterId")
                        .HasColumnType("int");

                    b.Property<byte?>("HomeErrors")
                        .HasColumnType("tinyint");

                    b.Property<int>("HomeFranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("HomeGameNumber")
                        .HasColumnType("int");

                    b.Property<byte?>("HomeHits")
                        .HasColumnType("tinyint");

                    b.Property<string>("HomeLineScore")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("HomeManagerId")
                        .HasColumnType("int");

                    b.Property<byte>("HomeTeamRuns")
                        .HasColumnType("tinyint");

                    b.Property<int?>("LosingPitcherId")
                        .HasColumnType("int");

                    b.Property<int?>("ParkAttendance")
                        .HasColumnType("int");

                    b.Property<int?>("SavingPitcherId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireFirstId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireHomeId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireLeftId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireRightId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireSecondId")
                        .HasColumnType("int");

                    b.Property<int?>("UmpireThirdId")
                        .HasColumnType("int");

                    b.Property<byte?>("VisitorErrors")
                        .HasColumnType("tinyint");

                    b.Property<int>("VisitorFranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorGameNumber")
                        .HasColumnType("int");

                    b.Property<byte?>("VisitorHits")
                        .HasColumnType("tinyint");

                    b.Property<string>("VisitorLineScore")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("VisitorManagerId")
                        .HasColumnType("int");

                    b.Property<byte>("VisitorRuns")
                        .HasColumnType("tinyint");

                    b.Property<int?>("WinningPitcherId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BallparkId");

                    b.HasIndex("GameDate");

                    b.HasIndex("GameWinningBatterId");

                    b.HasIndex("HomeFranchiseId");

                    b.HasIndex("HomeManagerId");

                    b.HasIndex("LosingPitcherId");

                    b.HasIndex("SavingPitcherId");

                    b.HasIndex("UmpireFirstId");

                    b.HasIndex("UmpireHomeId");

                    b.HasIndex("UmpireLeftId");

                    b.HasIndex("UmpireRightId");

                    b.HasIndex("UmpireSecondId");

                    b.HasIndex("UmpireThirdId");

                    b.HasIndex("VisitorFranchiseId");

                    b.HasIndex("VisitorManagerId");

                    b.HasIndex("WinningPitcherId");

                    b.HasIndex("GameDate", "HomeFranchiseId", "VisitorFranchiseId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameStatisticsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("AtBats")
                        .HasColumnType("smallint");

                    b.Property<short>("BaseOnBalls")
                        .HasColumnType("smallint");

                    b.Property<short>("Doubles")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<int>("GameId")
                        .HasColumnType("int");

                    b.Property<short>("GroundedIntoDoublePlay")
                        .HasColumnType("smallint");

                    b.Property<short>("Hit")
                        .HasColumnType("smallint");

                    b.Property<short>("HitByPitches")
                        .HasColumnType("smallint");

                    b.Property<string>("HomeVisitor")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<short>("Homeruns")
                        .HasColumnType("smallint");

                    b.Property<short>("IntentionalBb")
                        .HasColumnType("smallint");

                    b.Property<short>("PlateAppearances")
                        .HasColumnType("smallint");

                    b.Property<short>("Runs")
                        .HasColumnType("smallint");

                    b.Property<short>("RunsBattedIn")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeBunts")
                        .HasColumnType("smallint");

                    b.Property<short>("SacrificeFlies")
                        .HasColumnType("smallint");

                    b.Property<short>("StolenBases")
                        .HasColumnType("smallint");

                    b.Property<short>("Strikeouts")
                        .HasColumnType("smallint");

                    b.Property<short>("TimesCaughtStealing")
                        .HasColumnType("smallint");

                    b.Property<short>("Triples")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("GameId", "FranchiseId", "HomeVisitor");

                    b.ToTable("GameStatistics");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.LeagueModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LeagueCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("LeagueName")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.HasKey("Id");

                    b.HasIndex("LeagueCode")
                        .IsUnique();

                    b.ToTable("League");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PersonModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternateName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Bats")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("BirthCity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("BirthCountry")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("BirthName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("BirthStateProvince")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Cemetery")
                        .IsRequired()
                        .HasMaxLength(72)
                        .HasColumnType("nvarchar(72)");

                    b.Property<string>("CemeteryCity")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CemeteryCountry")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("CemeteryNote")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("nvarchar(1024)");

                    b.Property<string>("CemeteryStateProv")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("CoachDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CoachLastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeathCity")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("DeathCountry")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("DeathDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeathStateProvince")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<float?>("Height")
                        .HasColumnType("real");

                    b.Property<bool>("IsHof")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ManagerDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ManagerLastDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlayerDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PlayerLastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RetroSheetId")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("Throws")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("UmpireDebutDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UmpireLastDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UseName")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<float?>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("RetroSheetId")
                        .IsUnique();

                    b.HasIndex("Surname");

                    b.HasIndex("UseName");

                    b.ToTable("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PitchingModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<short>("Balks")
                        .HasColumnType("smallint");

                    b.Property<short>("BaseOnBalls")
                        .HasColumnType("smallint");

                    b.Property<short>("CompleteGames")
                        .HasColumnType("smallint");

                    b.Property<short>("EarnedRuns")
                        .HasColumnType("smallint");

                    b.Property<int>("FranchiseId")
                        .HasColumnType("int");

                    b.Property<short>("GamesFinished")
                        .HasColumnType("smallint");

                    b.Property<short>("GamesPitched")
                        .HasColumnType("smallint");

                    b.Property<short>("GamesStarted")
                        .HasColumnType("smallint");

                    b.Property<short>("HitBatsmen")
                        .HasColumnType("smallint");

                    b.Property<short>("Hits")
                        .HasColumnType("smallint");

                    b.Property<short>("InningsPitched")
                        .HasColumnType("smallint");

                    b.Property<short>("IntentionalBb")
                        .HasColumnType("smallint");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<short>("Runs")
                        .HasColumnType("smallint");

                    b.Property<short>("Saves")
                        .HasColumnType("smallint");

                    b.Property<short>("SeasonYear")
                        .HasColumnType("smallint");

                    b.Property<short>("Shutouts")
                        .HasColumnType("smallint");

                    b.Property<short>("Strikeouts")
                        .HasColumnType("smallint");

                    b.Property<short>("WildPitches")
                        .HasColumnType("smallint");

                    b.HasKey("Id");

                    b.HasIndex("FranchiseId");

                    b.HasIndex("PersonId", "FranchiseId", "SeasonYear");

                    b.ToTable("PitchingModel");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.BattingModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("BattingRecords")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany("BattingRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FieldingModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany()
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FranchiseModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.LeagueModel", "League")
                        .WithMany("Franchises")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("League");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameLineupModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Batter")
                        .WithMany("GameLineups")
                        .HasForeignKey("BatterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameLineups")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Batter");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.BallparkModel", "Ballpark")
                        .WithMany("Games")
                        .HasForeignKey("BallparkId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "GameWinningBatter")
                        .WithMany("GameWinningBatterGames")
                        .HasForeignKey("GameWinningBatterId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "HomeFranchise")
                        .WithMany("HomeGames")
                        .HasForeignKey("HomeFranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "HomeManager")
                        .WithMany("HomeManagerGames")
                        .HasForeignKey("HomeManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "LosingPitcher")
                        .WithMany("LosingPitcherGames")
                        .HasForeignKey("LosingPitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "SavingPitcher")
                        .WithMany("SavingPitcherGames")
                        .HasForeignKey("SavingPitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireFirst")
                        .WithMany("UmpireFirstGames")
                        .HasForeignKey("UmpireFirstId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireHome")
                        .WithMany("UmpireHomeGames")
                        .HasForeignKey("UmpireHomeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireLeft")
                        .WithMany("UmpireLeftGames")
                        .HasForeignKey("UmpireLeftId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireRight")
                        .WithMany("UmpireRightGames")
                        .HasForeignKey("UmpireRightId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireSecond")
                        .WithMany("UmpireSecondGames")
                        .HasForeignKey("UmpireSecondId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "UmpireThird")
                        .WithMany("UmpireThirdGames")
                        .HasForeignKey("UmpireThirdId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "VisitorFranchise")
                        .WithMany("VisitorGames")
                        .HasForeignKey("VisitorFranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "VisitorManager")
                        .WithMany("VisitorManagerGames")
                        .HasForeignKey("VisitorManagerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "WinningPitcher")
                        .WithMany("WinningPitcherGames")
                        .HasForeignKey("WinningPitcherId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ballpark");

                    b.Navigation("GameWinningBatter");

                    b.Navigation("HomeFranchise");

                    b.Navigation("HomeManager");

                    b.Navigation("LosingPitcher");

                    b.Navigation("SavingPitcher");

                    b.Navigation("UmpireFirst");

                    b.Navigation("UmpireHome");

                    b.Navigation("UmpireLeft");

                    b.Navigation("UmpireRight");

                    b.Navigation("UmpireSecond");

                    b.Navigation("UmpireThird");

                    b.Navigation("VisitorFranchise");

                    b.Navigation("VisitorManager");

                    b.Navigation("WinningPitcher");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameStatisticsModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("GameStatistics")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.GameModel", "Game")
                        .WithMany("GameStatistics")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PitchingModel", b =>
                {
                    b.HasOne("Retrosharp.Data.Model.FranchiseModel", "Franchise")
                        .WithMany("PitchingRecords")
                        .HasForeignKey("FranchiseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Retrosharp.Data.Model.PersonModel", "Person")
                        .WithMany("PitchingRecords")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Franchise");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.BallparkModel", b =>
                {
                    b.Navigation("Games");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.FranchiseModel", b =>
                {
                    b.Navigation("BattingRecords");

                    b.Navigation("GameStatistics");

                    b.Navigation("HomeGames");

                    b.Navigation("PitchingRecords");

                    b.Navigation("VisitorGames");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.GameModel", b =>
                {
                    b.Navigation("GameLineups");

                    b.Navigation("GameStatistics");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.LeagueModel", b =>
                {
                    b.Navigation("Franchises");
                });

            modelBuilder.Entity("Retrosharp.Data.Model.PersonModel", b =>
                {
                    b.Navigation("BattingRecords");

                    b.Navigation("GameLineups");

                    b.Navigation("GameWinningBatterGames");

                    b.Navigation("HomeManagerGames");

                    b.Navigation("LosingPitcherGames");

                    b.Navigation("PitchingRecords");

                    b.Navigation("SavingPitcherGames");

                    b.Navigation("UmpireFirstGames");

                    b.Navigation("UmpireHomeGames");

                    b.Navigation("UmpireLeftGames");

                    b.Navigation("UmpireRightGames");

                    b.Navigation("UmpireSecondGames");

                    b.Navigation("UmpireThirdGames");

                    b.Navigation("VisitorManagerGames");

                    b.Navigation("WinningPitcherGames");
                });
#pragma warning restore 612, 618
        }
    }
}
